//! Tolerant JSON-with-comments (JSONC) parser.
//!
//! Faithful port of `core/json/jsonc.py`.
//! JSONC dialect: `//` line comments, `/* */` block comments, trailing commas.
//! String-aware: comment markers inside quoted values are left untouched.

use serde_json::Value;

/// Remove `//` and `/* */` comments that are OUTSIDE string literals.
///
/// Walks the text tracking string state (and backslash escapes) so a
/// comment marker inside a quoted value — e.g. the `//` in `"https://…"` —
/// is left untouched. Direct port of Python `strip_jsonc_comments`.
pub fn strip_jsonc_comments(text: &str) -> String {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len();
    let mut out = String::with_capacity(text.len());
    let mut i = 0;
    let mut in_str = false;

    while i < n {
        let c = chars[i];
        if in_str {
            out.push(c);
            if c == '\\' && i + 1 < n {
                // keep the escaped char verbatim (matches Python `out.append(text[i+1])`)
                out.push(chars[i + 1]);
                i += 2;
                continue;
            }
            if c == '"' {
                in_str = false;
            }
            i += 1;
            continue;
        }
        if c == '"' {
            in_str = true;
            out.push(c);
            i += 1;
            continue;
        }
        // `//` line comment — skip to end of line (newline stays, like Python)
        if c == '/' && i + 1 < n && chars[i + 1] == '/' {
            i += 2;
            while i < n && chars[i] != '\n' {
                i += 1;
            }
            continue;
        }
        // `/* */` block comment — skip to `*/`; if unclosed, skip to end of string
        if c == '/' && i + 1 < n && chars[i + 1] == '*' {
            i += 2;
            while i + 1 < n && !(chars[i] == '*' && chars[i + 1] == '/') {
                i += 1;
            }
            i += 2; // skip the closing `*/`; if past end that is fine (loop guard)
            continue;
        }
        out.push(c);
        i += 1;
    }
    out
}

/// Remove trailing commas before `}` or `]`.
///
/// Mirrors Python `re.sub(r",(\s*[}\]])", r"\1", s)` — replaces `,` followed
/// by optional whitespace then a closing bracket with just the whitespace +
/// bracket (the comma is dropped).
fn remove_trailing_commas(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let n = chars.len();
    let mut out = String::with_capacity(n);
    let mut i = 0;
    while i < n {
        if chars[i] == ',' {
            // Look ahead: optional whitespace then `}` or `]`
            let mut j = i + 1;
            while j < n
                && (chars[j] == ' '
                    || chars[j] == '\t'
                    || chars[j] == '\n'
                    || chars[j] == '\r')
            {
                j += 1;
            }
            if j < n && (chars[j] == '}' || chars[j] == ']') {
                // Drop the comma; the whitespace and bracket will be pushed
                // in subsequent iterations.
                i += 1;
                continue;
            }
        }
        out.push(chars[i]);
        i += 1;
    }
    out
}

/// Parse JSONC `text`: strip comments (string-aware) and tolerate trailing
/// commas, then parse as JSON. Raises a `serde_json::Error` on genuinely
/// malformed input, like `json.loads` in Python.
pub fn load_jsonc(text: &str) -> Result<Value, serde_json::Error> {
    let cleaned = strip_jsonc_comments(text);
    let cleaned = remove_trailing_commas(&cleaned);
    serde_json::from_str(&cleaned)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // ---------- strip_jsonc_comments golden vectors ----------
    // Generated by running the original Python core/json/jsonc.py

    #[test]
    fn strip_line_comment() {
        assert_eq!(
            strip_jsonc_comments("{ \"a\": 1 // comment\n}"),
            "{ \"a\": 1 \n}"
        );
    }

    #[test]
    fn strip_block_comment() {
        assert_eq!(
            strip_jsonc_comments("{ \"a\": /* comment */ 1 }"),
            "{ \"a\":  1 }"
        );
    }

    #[test]
    fn url_in_string_preserved() {
        let s = r#"{"url": "https://example.com"}"#;
        assert_eq!(strip_jsonc_comments(s), s);
    }

    #[test]
    fn trailing_comma_object_unchanged_by_strip() {
        let s = r#"{"a": 1, }"#;
        assert_eq!(strip_jsonc_comments(s), s);
    }

    #[test]
    fn trailing_comma_array_unchanged_by_strip() {
        let s = "[1, 2, 3, ]";
        assert_eq!(strip_jsonc_comments(s), s);
    }

    #[test]
    fn full_jsonc_strip() {
        assert_eq!(
            strip_jsonc_comments("{\"a\": 1, // comment\n\"b\": 2, /* block */}"),
            "{\"a\": 1, \n\"b\": 2, }"
        );
    }

    #[test]
    fn escaped_quote_in_string() {
        // Python: '{"key": "value \\" rest"}' → unchanged
        let s = "{ \"key\": \"value \\\" rest\"}";
        assert_eq!(strip_jsonc_comments(s), s);
    }

    #[test]
    fn multiline_block_comment() {
        assert_eq!(
            strip_jsonc_comments("{\"a\": 1, /* line1\nline2 */ \"b\": 2}"),
            "{\"a\": 1,  \"b\": 2}"
        );
    }

    #[test]
    fn empty_string() {
        assert_eq!(strip_jsonc_comments(""), "");
    }

    #[test]
    fn only_line_comment() {
        // newline stays; comment content gone
        assert_eq!(strip_jsonc_comments("// just a comment\n"), "\n");
    }

    #[test]
    fn hash_not_comment_in_jsonc() {
        // JSONC does NOT strip #; that is the config-flavor (utils.rs)
        let s = "{\"color\": \"#fff\"}";
        assert_eq!(strip_jsonc_comments(s), s);
    }

    #[test]
    fn double_slash_in_string_preserved() {
        let s = r#"{"path": "/usr//local"}"#;
        assert_eq!(strip_jsonc_comments(s), s);
    }

    #[test]
    fn unclosed_block_comment() {
        // Python skips to end of string when `*/` is absent
        assert_eq!(strip_jsonc_comments("{\"a\": /* unclosed"), "{\"a\": ");
    }

    #[test]
    fn multi_comments() {
        assert_eq!(
            strip_jsonc_comments(
                "// first\n{\"a\": 1, // inline\n\"b\": /* block */ 2\n}"
            ),
            "\n{\"a\": 1, \n\"b\":  2\n}"
        );
    }

    #[test]
    fn backslash_escape_preserved() {
        let s = "{\"a\": \"hello\\\\n world\"}";
        assert_eq!(strip_jsonc_comments(s), s);
    }

    // ---------- load_jsonc golden vectors ----------

    #[test]
    fn parse_line_comment() {
        let v = load_jsonc("{ \"a\": 1 // comment\n}").unwrap();
        assert_eq!(v["a"], 1);
    }

    #[test]
    fn parse_block_comment() {
        let v = load_jsonc("{ \"a\": /* comment */ 1 }").unwrap();
        assert_eq!(v["a"], 1);
    }

    #[test]
    fn parse_url_in_string() {
        let v = load_jsonc(r#"{"url": "https://example.com"}"#).unwrap();
        assert_eq!(v["url"], "https://example.com");
    }

    #[test]
    fn parse_trailing_comma_object() {
        let v = load_jsonc(r#"{"a": 1, }"#).unwrap();
        assert_eq!(v["a"], 1);
    }

    #[test]
    fn parse_trailing_comma_array() {
        let v = load_jsonc("[1, 2, 3, ]").unwrap();
        assert_eq!(v, json!([1, 2, 3]));
    }

    #[test]
    fn parse_full_jsonc() {
        let v = load_jsonc("{\"a\": 1, // comment\n\"b\": 2, /* block */}").unwrap();
        assert_eq!(v["a"], 1);
        assert_eq!(v["b"], 2);
    }

    #[test]
    fn parse_multiline_block_comment() {
        let v = load_jsonc("{\"a\": 1, /* line1\nline2 */ \"b\": 2}").unwrap();
        assert_eq!(v["a"], 1);
        assert_eq!(v["b"], 2);
    }

    #[test]
    fn parse_empty_errors() {
        assert!(load_jsonc("").is_err());
    }

    #[test]
    fn parse_only_comment_errors() {
        assert!(load_jsonc("// just a comment\n").is_err());
    }

    #[test]
    fn parse_nested_trailing_commas() {
        let v = load_jsonc(r#"{"a": {"b": 1, }, "c": [1, 2, ], }"#).unwrap();
        assert_eq!(v["a"]["b"], 1);
        assert_eq!(v["c"], json!([1, 2]));
    }

    #[test]
    fn parse_unclosed_block_comment_errors() {
        assert!(load_jsonc("{\"a\": /* unclosed").is_err());
    }

    #[test]
    fn parse_booleans_null() {
        let v = load_jsonc(r#"{"t":true,"f":false,"n":null}"#).unwrap();
        assert_eq!(v["t"], true);
        assert_eq!(v["f"], false);
        assert_eq!(v["n"], Value::Null);
    }

    #[test]
    fn parse_numbers() {
        let v = load_jsonc("[1, 2.5, -3, 0]").unwrap();
        assert_eq!(v, json!([1, 2.5, -3, 0]));
    }

    #[test]
    fn parse_multi_comments() {
        let v =
            load_jsonc("// first\n{\"a\": 1, // inline\n\"b\": /* block */ 2\n}").unwrap();
        assert_eq!(v["a"], 1);
        assert_eq!(v["b"], 2);
    }

    #[test]
    fn parse_deep_nested() {
        let v = load_jsonc(r#"{"a":{"b":{"c":{"d":1}}}}"#).unwrap();
        assert_eq!(v["a"]["b"]["c"]["d"], 1);
    }

    #[test]
    fn parse_unicode() {
        let v = load_jsonc(r#"{"key": "é"}"#).unwrap();
        assert_eq!(v["key"], "é");
    }
}
