[package]
name = "mantishack_smt_solver"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "mantishack_smt_solver"
crate-type = ["cdylib", "rlib"]

[features]
default = []
python = ["dep:pyo3"]

[dependencies]
pyo3 = { workspace = true, optional = true }
regex = { workspace = true }

[dev-dependencies]
