use std::fs::File;
use std::io::{Read, Seek, SeekFrom};
use std::path::Path;
use std::sync::OnceLock;

use regex::Regex;

pub const DEFAULT_EXCLUDES: &[&str] = &[
    "*_test.*",
    "test_*",
    "*_mock.*",
    "mock_*",
    "*_spec.*",
    "__tests__/",
    "tests/",
    "test/",
    "spec/",
    "testing/",
    "fixtures/",
    "__fixtures__/",
    "testdata/",
    "test-data/",
    "node_modules/",
    "vendor/",
    "third_party/",
    "third-party/",
    "external/",
    "deps/",
    "dependencies/",
    "venv/",
    ".venv/",
    "env/",
    ".env/",
    "virtualenv/",
    "__pycache__/",
    ".pytest_cache/",
    ".tox/",
    ".eggs/",
    "*.egg-info/",
    "site-packages/",
    "dist/",
    "build/",
    "target/",
    "out/",
    "output/",
    "bin/",
    "obj/",
    "cmake-build-*/",
    ".git/",
    ".svn/",
    ".hg/",
    ".bzr/",
    ".idea/",
    ".vscode/",
    ".vs/",
    "*.swp",
    "*.swo",
    "*.min.js",
    "*.min.css",
    "*.bundle.js",
    "*.bundle.css",
    "*.generated.*",
    "*.auto.*",
    "*_generated.*",
    "*_pb2.py",
    "*_pb2_grpc.py",
    "*.pb.go",
    "*.pb.cc",
    "generated/",
    "gen/",
    "autogen/",
    "docs/",
    "doc/",
    "documentation/",
    "examples/",
    "example/",
    "samples/",
    "sample/",
    "demo/",
];

pub const ROOT_ANCHORED_EXCLUDE_DIRS: &[&str] = &[
    "examples",
    "example",
    "samples",
    "sample",
    "demo",
    "docs",
    "doc",
    "documentation",
];

pub const GENERATED_MARKERS: &[&str] = &[
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
    "do not modify",
    "generated by",
    "generated from",
    "@generated",
    "// code generated",
    "# generated",
    "/* generated",
    "this file was generated",
    "machine generated",
];

pub fn is_binary_file(filepath: &Path, sample_size: usize) -> bool {
    let mut file = match File::open(filepath) {
        Ok(file) => file,
        Err(_) => return true,
    };
    let mut head = vec![0_u8; sample_size];
    let head_len = match file.read(&mut head) {
        Ok(read) => read,
        Err(_) => return true,
    };
    if head[..head_len].contains(&0) {
        return true;
    }

    let size = match file.seek(SeekFrom::End(0)) {
        Ok(size) => size,
        Err(_) => return false,
    };
    if size > (sample_size as u64).saturating_mul(2) {
        if file
            .seek(SeekFrom::Start(size.saturating_sub(sample_size as u64)))
            .is_err()
        {
            return true;
        }
        let mut tail = vec![0_u8; sample_size];
        return match file.read(&mut tail) {
            Ok(read) => tail[..read].contains(&0),
            Err(_) => true,
        };
    }
    false
}

fn comment_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^\s*(#|//|/\*|\*|--|<!--)").unwrap())
}

pub fn is_generated_file(content: &str, check_lines: usize) -> bool {
    content.split('\n').take(check_lines).any(|line| {
        comment_re().is_match(line)
            && GENERATED_MARKERS
                .iter()
                .any(|marker| line.to_lowercase().contains(marker))
    })
}

fn fnmatch(pattern: &str, value: &str) -> bool {
    let mut regex = String::from(r"\A");
    let chars: Vec<char> = pattern.chars().collect();
    let mut index = 0;
    while index < chars.len() {
        match chars[index] {
            '*' => regex.push_str(".*"),
            '?' => regex.push('.'),
            '[' => {
                let mut end = index + 1;
                if end < chars.len() && matches!(chars[end], '!' | ']') {
                    end += 1;
                }
                while end < chars.len() && chars[end] != ']' {
                    end += 1;
                }
                if end >= chars.len() {
                    regex.push_str(r"\[");
                } else {
                    let mut body: String = chars[index + 1..end].iter().collect();
                    if let Some(rest) = body.strip_prefix('!') {
                        body = format!("^{rest}");
                    }
                    regex.push('[');
                    regex.push_str(&body.replace('\\', r"\\"));
                    regex.push(']');
                    index = end;
                }
            }
            character => regex.push_str(&regex::escape(&character.to_string())),
        }
        index += 1;
    }
    regex.push_str(r"\z");
    Regex::new(&regex)
        .map(|compiled| compiled.is_match(value))
        .unwrap_or(false)
}

fn path_parts(filepath: &str) -> Vec<&str> {
    filepath.split(std::path::MAIN_SEPARATOR).collect()
}

fn basename(filepath: &str) -> &str {
    filepath
        .rsplit(std::path::MAIN_SEPARATOR)
        .next()
        .unwrap_or(filepath)
}

fn matched_pattern(filepath: &str, exclude_patterns: &[String]) -> Option<String> {
    let filepath_lower = filepath.to_lowercase();
    let parts = path_parts(&filepath_lower);

    for pattern in exclude_patterns {
        let pattern_lower = pattern.to_lowercase();
        if pattern.ends_with('/') {
            let dir_name = &pattern_lower[..pattern_lower.len() - 1];
            if dir_name.contains(['*', '?', '[']) {
                if parts.iter().any(|part| fnmatch(dir_name, part)) {
                    return Some(pattern.clone());
                }
            } else if ROOT_ANCHORED_EXCLUDE_DIRS.contains(&dir_name) {
                if parts.first().copied() == Some(dir_name) {
                    return Some(pattern.clone());
                }
            } else if parts.contains(&dir_name) {
                return Some(pattern.clone());
            }
        } else if pattern.contains('*') {
            if fnmatch(&pattern_lower, basename(&filepath_lower))
                || fnmatch(&pattern_lower, &filepath_lower)
            {
                return Some(pattern.clone());
            }
        } else if parts.contains(&pattern_lower.as_str())
            || pattern_lower == basename(&filepath_lower)
        {
            return Some(pattern.clone());
        }
    }
    None
}

pub fn should_exclude(filepath: &str, exclude_patterns: &[String]) -> bool {
    matched_pattern(filepath, exclude_patterns).is_some()
}

pub fn match_exclusion_reason(
    filepath: &str,
    exclude_patterns: &[String],
) -> (bool, Option<&'static str>, Option<String>) {
    match matched_pattern(filepath, exclude_patterns) {
        Some(pattern) => (true, Some("pattern_match"), Some(pattern)),
        None => (false, None, None),
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::*;

    fn defaults() -> Vec<String> {
        DEFAULT_EXCLUDES.iter().map(ToString::to_string).collect()
    }

    #[test]
    fn directory_and_glob_patterns_match_python() {
        assert!(should_exclude(
            "project/tests/test_foo.py",
            &["tests/".into()]
        ));
        assert!(!should_exclude("project/src/foo.py", &["tests/".into()]));
        assert!(should_exclude("test_foo.py", &["test_*".into()]));
        assert!(should_exclude("foo_test.py", &["*_test.*".into()]));
        assert!(!should_exclude("foo.py", &["test_*".into()]));
    }

    #[test]
    fn root_anchoring_matches_python() {
        let patterns = defaults();
        for path in [
            "src/main/java/org/springframework/samples/petclinic/Owner.java",
            "src/main/java/com/app/examples/PaymentExample.java",
            "app/demo/widget.py",
            "lib/doc/Renderer.java",
        ] {
            assert!(!should_exclude(path, &patterns), "{path}");
        }
        for path in ["examples/Demo.java", "samples/app.py", "docs/conf.py"] {
            assert!(should_exclude(path, &patterns), "{path}");
        }
    }

    #[test]
    fn generated_markers_must_be_in_comments() {
        assert!(is_generated_file("# auto-generated by protoc\ncode", 10));
        assert!(is_generated_file("  // DO NOT EDIT\ncode", 10));
        assert!(!is_generated_file(
            "message = 'automatically generated'\ncode",
            10
        ));
    }

    #[test]
    fn binary_probe_checks_head_and_tail() {
        let dir = tempdir().unwrap();
        let text = dir.path().join("text");
        fs::write(&text, b"hello world").unwrap();
        assert!(!is_binary_file(&text, 4));

        let binary = dir.path().join("binary");
        let mut bytes = vec![b'x'; 20];
        bytes[19] = 0;
        fs::write(&binary, bytes).unwrap();
        assert!(is_binary_file(&binary, 4));
        assert!(is_binary_file(&dir.path().join("missing"), 8192));
    }
}
